# Generated by Django 5.0.6 on 2024-05-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("pronouns", models.CharField(blank=True, max_length=255, null=True)),
                ("socials", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("platform", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("estimated_time", models.DurationField()),
                ("planning_start_at", models.DateTimeField()),
                ("planning_end_at", models.DateTimeField()),
                ("actual_start_at", models.DateTimeField(blank=True, null=True)),
                ("actual_end_at", models.DateTimeField(blank=True, null=True)),
                ("run_segment_index", models.IntegerField()),
                ("run_index", models.IntegerField()),
                ("is_intermission", models.BooleanField(default=False)),
                ("commenters", models.ManyToManyField(related_name="comments", to="runs.person")),
                ("runners", models.ManyToManyField(related_name="runs", to="runs.person")),
            ],
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.UniqueConstraint(
                fields=("run_segment_index", "run_index"), name="run_order"
            ),
        ),
    ]
