# Generated by Django 5.0.6 on 2024-05-19 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="run",
            name="run_order",
        ),
        migrations.RemoveField(
            model_name="run",
            name="run_segment_index",
        ),
        migrations.AddField(
            model_name="run",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="run",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="run",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name="eventdata",
            name="current_run",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="runs.run"
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="event",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="runs.eventdata"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["event", "run_index"], name="runs_run_event_i_655e5b_idx"),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.UniqueConstraint(fields=("event", "run_index"), name="run_order"),
        ),
    ]
