# Generated by Django 5.0.6 on 2024-05-19 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0002_eventdata_remove_run_run_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="runs.eventdata"
            ),
        ),
    ]
