# Generated by Django 5.0.6 on 2024-05-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0004_remove_run_is_current_eventdata_shift_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="run",
            old_name="commenters",
            new_name="commentators",
        ),
    ]
