# Generated by Django 5.0.6 on 2024-05-19 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0005_rename_commenters_run_commentators"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdata",
            name="event_end_on",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="eventdata",
            name="event_start_on",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
