# Generated by Django 5.0.6 on 2024-05-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0006_eventdata_event_end_on_eventdata_event_start_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="trigger_warning",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
