# Generated by Django 5.0.6 on 2024-05-23 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0008_alter_run_runners"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventdata",
            name="event_end_on",
        ),
        migrations.RemoveField(
            model_name="eventdata",
            name="event_start_on",
        ),
        migrations.AddField(
            model_name="eventdata",
            name="event_end_at",
            field=models.DateTimeField(
                auto_created=True, default=datetime.datetime(2024, 5, 23, 20, 30, 7, 658739, tzinfo=datetime.UTC),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventdata",
            name="event_start_at",
            field=models.DateTimeField(
                auto_created=True, default=datetime.datetime(2024, 5, 23, 20, 30, 23, 947514, tzinfo=datetime.UTC),
            ),
            preserve_default=False,
        ),
    ]
