# Generated by Django 5.0.6 on 2024-05-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0010_run_obs_scene_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="rtmp_host",
            field=models.URLField(blank=True, null=True),
        ),
    ]
